### ISSUE TITLE
nonce required for test OP-nonce-NoReq-noncode when using 'code token' flow

### ISSUE THREAD

**Issue by djfwong** [rohe/oidctest#111]
Was wondering why this test expects a nonce, it seems a nonce is only expected when id_token is sent in the request to prevent replay attacks. For this test, only 'code token' is sent, and we expect a nonce which should be optional.

Is it a requirement to pass this test for hybrid (code token) certification, if so, can I get some guidance on this issue on whether it is an issue with the OP implementation or the OP conformance test tool.

Thanks.

**Comment by zandbelt** [comment]
I think you may have encountered an issue with the test suite indeed:

The `nonce` is optional for the Client to provide in case the `id_token` is not delivered in the front channel. See https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken which says about the nonce
> When using the Hybrid Flow, these additional requirements for the following ID Token Claims apply to an ID Token returned from the Authorization Endpoint:

In this `OP-nonce-NoReq-noncode` case a nonce is **not** sent but then for the `code token` response type the `id_token` is **not** returned from the Authorization Endpoint. I believe you're observing that not throwing an error and continue as normal makes the test suite show a failure, right?

If so I believe @selfissued and @rohe should comment.

**Comment by djfwong** [comment]
Correct the test is throwing an error and saying it is expecting an error. A python exception occurs

**Comment by zandbelt** [comment]
Please also paste the python error for our convenience.. :-)

**Comment by djfwong** [comment]
`********************************************************************************
Something went seriously wrong, please tell us at certification@oidf.org
********************************************************************************


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/optt/__init__.py", line 288, in authz_post
    response=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.7-py3.6.egg/otest/aus/tool.py", line 225, in async_response
    response=response)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.7-py3.6.egg/otest/aus/request.py", line 349, in parse_response
    self.expected_error_response(response)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.7-py3.6.egg/otest/aus/request.py", line 67, in expected_error_response
    raise Break("Did not receive expected error")
otest.Break: Did not receive expected error`

**Comment by selfissued** [comment]
Section 3.3.2.11.  ID Token (in the Hybrid Flow section 3.3) at https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken says:

The contents of the ID Token are as described in Section 2. When using the Hybrid Flow, these additional requirements for the following ID Token Claims apply to an ID Token returned from the Authorization Endpoint: 

nonce
Use of the nonce Claim is REQUIRED for this flow.


Requiring a nonce for this Hybrid flow response_type value is not a test bug.  Can a maintainer of this project please close this bug on this basis?  I apparently don't have the rights to do so.  Thanks.

**Comment by zandbelt** [comment]
the point is that there is *no* id_token returned from the authorization endpoint in "code token" which voids the additional requirements

**Comment by zandbelt** [comment]
Ok, then the sentence in the spec should omit the " returned from the Authorization Endpoint" postfix since it also applies to an ID token returned from the Token Endpoint.

**Comment by zandbelt** [comment]
@djfwong so your implementation should throw an error on not receiving a `nonce` in the CT flow

**Comment by zandbelt** [comment]
See also: https://bitbucket.org/openid/connect/issues/1052/make-clear-that-nonce-is-always-required

**Comment by b---c** [comment]
https://bitbucket.org/openid/connect/issues/1052 was closed but the *friendly* dissuasion around it resulted in https://bitbucket.org/openid/connect/issues/972 being reopened and resolved with a different and now correct outcome. As such, I'd respectfully request that this issue be addressed so as to not have a test that requires the nonce when the response type is 'code token'.

**Comment by zandbelt** [comment]
We'll follow up in the openid-certification repository in openid-certification/oidctest#14
