### ISSUE TITLE
Dynamic client registration configuration should include a way of providing an initial token

### ISSUE THREAD

**Issue by travisspencer** [rohe/oidctest#61]
[Section 3](http://openid.net/specs/openid-connect-registration-1_0.html#ClientRegistration) of the OIDC dynamic client registration spec says that 

>  The OpenID Provider MAY require an Initial Access Token that is provisioned out-of-band (in a manner that is out of scope for this specification) to restrict registration requests to only authorized Clients or developers. 

When configuring an OP entity in the `op_test` tool, there is no way to provide this initial token. As a result, there is no way for an OP that requires authentication of the registration endpoint to be tested. 

Something like the following mockup is needed:

![screen shot 2017-08-05 at 10 29 57 am](https://user-images.githubusercontent.com/2499235/28994249-91fdf74c-79c9-11e7-943d-507f902dbef9.png)

If an initial access token is configured in such a way, then the test tool should send it to the OP in an `Authorization` header (per RFC  6750) when registering the client.

**Comment by travisspencer** [comment]
@rohe should issues like this be reported in another repo, or does this one work?

**Comment by rohe** [comment]
It should be reported here [https://github.com/openid-certification/oidctest/issues](https://github.com/openid-certification/oidctest/issues)
